GET http://localhost:5050/menus/64997ab6c6005351d3dc333c


#######

GET http://localhost:5050/cooks/64997ab6c6005351d3dc333c

#######


POST http://localhost:5050/menus/64997ab6c6005351d3dc333c HTTP/1.1
content-type: application/json

{
  "name": "Menù inverno",
  "price": 30,
  "courses": [
    {"courseName": "Tagliere di salumi e formaggi", "courseType": "antipasto"},
    {"courseName": "Fettuccine al ragù", "courseType": "primo"},
    {"courseName": "Salti in bocca alla romana", "courseType": "secondo"},
    {"courseName": "Patate al forno", "courseType": "contorno"},
    {"courseName": "Dolce della casa", "courseType": "dolce"}
  ]
}


#######

PATCH  http://localhost:5050/cooks/64997ab6c6005351d3dc333c HTTP/1.1
content-type: application/json

{
  "description": "Sono bravissimo",
  "towns": ["Roma", "Viterbo"],
  "available": true
}


#######


DELETE  http://localhost:5050/cooks/649979e1b9def7b2405ad9ca
