GET http://localhost:5050/requests

###################

GET http://localhost:5050/requests/64b270dd7c4748a7b0f6d204

###################


GET http://localhost:5050/requests/byUserId/649db085b56ed6875102c636

###################

GET http://localhost:5050/requests/byCookId/64aae15390ef355fbf9b2f92

###################



POST http://localhost:5050/requests HTTP/1.1
content-type: application/json

{
  "user": "649db085b56ed6875102c636",
  "cook": "64aae15390ef355fbf9b2f92",
  "date": "2023-08-05",
  "from": "20:00",
  "to": "23:00",
  "place": {
    "street": "Via Mario Carotenuto 52/B",
    "zipCode": "00125",
    "town": "Roma",
    "province": "Roma"
  },
  "menu": "64b1240dea47d3b567243ce2",
  "state": "created",
  "owner": "user"
}

####################
PATCH http://localhost:5050/requests/64b270dd7c4748a7b0f6d204 HTTP/1.1
content-type: application/json

{
    "state": "sent"
}

############

DELETE http://localhost:5050/requests/64b270dd7c4748a7b0f6d204