
GET http://localhost:5050/users


#######

GET http://localhost:5050/users/649963c984aab1801d869dd9

#######


POST http://localhost:5050/users HTTP/1.1
content-type: application/json

{
  "firstName": "Andrea",
  "lastName": "Campetella",
  "email": "andrea.campetella@libero.it",
  "password": "tallaro123",
  "birthDate": "1974-07-28",
  "role": "admin"
}


#######

PATCH  http://localhost:5050/users/6499623ae33912dfab18b793 HTTP/1.1
content-type: application/json

{
  "phones": ["334/1234567", "335/7654321"]
}


#######


DELETE  http://localhost:5050/users/649963c984aab1801d869dd9
